"use client";

import { useState, useCallback, useEffect } from "react";
import { QRCodeSVG } from "qrcode.react";

// ─── Types ─────────────────────────────────────────────────────────────────

interface SessionQRCodeProps {
  /** 6-character project code displayed beneath the QR. */
  projectCode: string;
  /** Session password, togglable visibility. */
  password: string;
  /**
   * Base origin for the audience URL.
   * Defaults to `window.location.origin` on the client.
   */
  baseUrl?: string;
  /**
   * Short-lived audience token generated by POST /api/audience/token.
   * When provided the QR code encodes a token URL (?t=…) instead of
   * the password URL (?p=…), allowing passwordless one-tap access.
   */
  token?: string;
}

// ─── Helpers ───────────────────────────────────────────────────────────────

function buildAudienceUrl(
  baseUrl: string,
  projectCode: string,
  password: string,
  token?: string
): string {
  if (token) {
    return `${baseUrl}/audience/${projectCode}?t=${token}`;
  }
  return `${baseUrl}/audience/${projectCode}?p=${password}`;
}

// ─── Icon: Eye (visible) ───────────────────────────────────────────────────

function EyeIcon() {
  return (
    <svg
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  );
}

// ─── Icon: Eye Off (hidden) ────────────────────────────────────────────────

function EyeOffIcon() {
  return (
    <svg
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94" />
      <path d="M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19" />
      <line x1="1" y1="1" x2="23" y2="23" />
    </svg>
  );
}

// ─── Icon: Copy ────────────────────────────────────────────────────────────

function CopyIcon() {
  return (
    <svg
      width="14"
      height="14"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
  );
}

// ─── Icon: Check (copy success) ────────────────────────────────────────────

function CheckIcon() {
  return (
    <svg
      width="14"
      height="14"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2.5"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}

// ─── Main component ────────────────────────────────────────────────────────

export function SessionQRCode({
  projectCode,
  password,
  baseUrl,
  token,
}: SessionQRCodeProps) {
  const [resolvedBaseUrl, setResolvedBaseUrl] = useState(baseUrl ?? "");
  const [showPassword, setShowPassword] = useState(false);
  const [copied, setCopied] = useState(false);

  // Resolve window.location.origin on mount when baseUrl is not provided
  useEffect(() => {
    if (!baseUrl) {
      setResolvedBaseUrl(window.location.origin);
    }
  }, [baseUrl]);

  const audienceUrl = buildAudienceUrl(resolvedBaseUrl, projectCode, password, token);

  // ─── Copy handler ───────────────────────────────────────────────────

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(audienceUrl);
      setCopied(true);
      // Reset after 2 seconds
      const timer = setTimeout(() => setCopied(false), 2000);
      return () => clearTimeout(timer);
    } catch {
      // Fallback: select + copy via execCommand
      const textarea = document.createElement("textarea");
      textarea.value = audienceUrl;
      textarea.style.position = "fixed";
      textarea.style.opacity = "0";
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [audienceUrl]);

  // ─── Render ─────────────────────────────────────────────────────────

  return (
    <div className="flex flex-col items-center gap-5 p-6 rounded-2xl border border-gray-800 bg-gray-900">
      {/* QR Code */}
      <div className="relative group">
        {/* Subtle glow behind QR on hover */}
        <div
          className="absolute inset-0 -z-10 rounded-xl blur-lg bg-indigo-600/10 opacity-0 group-hover:opacity-100 transition-opacity duration-500"
          aria-hidden="true"
        />

        {/* QR container with border */}
        <div className="rounded-xl border border-gray-800 bg-white/95 p-3 shadow-lg shadow-black/20">
          {resolvedBaseUrl ? (
            <>
              {/* Desktop size */}
              <div className="hidden sm:block">
                <QRCodeSVG
                  value={audienceUrl}
                  size={200}
                  bgColor="transparent"
                  fgColor="#1e1b4b"
                  level="M"
                  includeMargin={false}
                />
              </div>

              {/* Mobile size */}
              <div className="sm:hidden">
                <QRCodeSVG
                  value={audienceUrl}
                  size={156}
                  bgColor="transparent"
                  fgColor="#1e1b4b"
                  level="M"
                  includeMargin={false}
                />
              </div>
            </>
          ) : (
            /* Placeholder while origin resolves */
            <div
              className="hidden sm:flex sm:w-[200px] sm:h-[200px] w-[156px] h-[156px] items-center justify-center"
              aria-label="QR 코드 생성 중"
            >
              <div className="w-10 h-10 rounded-full border-2 border-indigo-500 border-t-transparent animate-spin" />
            </div>
          )}
        </div>
      </div>

      {/* Project code */}
      <div className="flex flex-col items-center gap-1">
        <span className="text-xs text-gray-500 uppercase tracking-widest">
          프로젝트 코드
        </span>
        <span className="text-2xl font-mono font-bold tracking-[0.2em] text-indigo-300 select-all">
          {projectCode}
        </span>
      </div>

      {/* Password row */}
      <div className="flex items-center gap-2">
        <span className="text-xs text-gray-500 uppercase tracking-widest">
          비밀번호
        </span>

        <span className="font-mono text-sm text-gray-200 select-all tracking-wider">
          {showPassword ? password : "••••••"}
        </span>

        <button
          type="button"
          onClick={() => setShowPassword((v) => !v)}
          className="text-gray-600 hover:text-indigo-400 transition-colors"
          aria-label={showPassword ? "비밀번호 숨기기" : "비밀번호 보여주기"}
        >
          {showPassword ? <EyeOffIcon /> : <EyeIcon />}
        </button>
      </div>

      {/* Divider */}
      <div className="w-full border-t border-gray-800" />

      {/* Copy Link button */}
      <button
        type="button"
        onClick={handleCopy}
        className={[
          "group/btn flex items-center gap-2 rounded-lg border px-4 py-2 text-sm font-medium transition-all duration-200",
          copied
            ? "border-emerald-600 bg-emerald-900/20 text-emerald-300"
            : "border-gray-700 bg-gray-800 text-gray-200 hover:border-indigo-500 hover:bg-gray-700 hover:text-indigo-200 active:scale-95",
        ].join(" ")}
        aria-label="링크 복사"
      >
        {copied ? <CheckIcon /> : <CopyIcon />}
        {copied ? "복사 완료" : "링크 복사"}
      </button>

      {/* URL preview — truncated for long origins */}
      {resolvedBaseUrl && (
        <p className="text-xs text-gray-600 text-center truncate max-w-full font-mono select-all">
          {audienceUrl}
        </p>
      )}
    </div>
  );
}
